### ISSUE TITLE
-var-create: unable to create variable object

### ISSUE THREAD

**Issue by yyMoming** [JetBrains/clion-debugger-plugin-stub#1]
When I debugged my C++ codes，an exception existed "-var-create: unable to create variable object". However, when I ran the whole codes, there is not any error. Here is my settings of "Toolchains".

Environment: mingw32 (version: w64 6.0)
Cmake: Bundled
Debugger: MinGW-w64 GDB version8.1

**Comment by elmot** [comment]
I think you are reached a wrong place. This stub project does not work with gdb at all. However, the message you mentioned does not affect code functionality, it means that the debugger does not understand your your watch expression. There might be multiple reasons: no debug info in the project binary, mistyped expression etc.
